# Generated by Django 3.2.19 on 2026-08-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20260801_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Internal note visible only to admins. Not shown to users.'),
        ),
        migrations.CreateModel(
            name='ReportedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive Content'), ('harassment', 'Harassment'), ('false_info', 'False Information'), ('spoiler', 'Spoiler'), ('other', 'Other')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Optional additional context from the reporter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_reviews', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='movies.review')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who last acted on this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportedreview',
            index=models.Index(fields=['status', '-reported_at'], name='movies_repo_status_a8f677_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportedreview',
            unique_together={('review', 'reported_by')},
        ),
    ]
