# Generated by Django 3.2.19 on 2026-08-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260801_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set false for broken/maintenance seats'),
        ),
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(blank=True, default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('regular', 'Executive / Regular'), ('premium', 'Premium'), ('recliner', 'Recliner / VIP')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(blank=True, choices=[('U', 'U - Unrestricted Public Exhibition'), ('U/A', 'U/A - Parental Guidance Suggested'), ('U/A 13+', 'U/A 13+ - Suitable for 13 years and above'), ('U/A 16+', 'U/A 16+ - Suitable for 16 years and above'), ('A', 'A - Restricted to Adults'), ('S', 'S - Restricted to Specialized Audiences')], help_text='e.g. U, U/A, U/A 13+, A', max_length=20),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Screen 1, Audi 2 - IMAX', max_length=100)),
                ('screen_type', models.CharField(choices=[('2D', 'Standard 2D'), ('3D', '3D Screen'), ('IMAX_3D', 'IMAX 3D'), ('4DX', '4DX Motion'), ('DOLBY', 'Dolby Atmos')], default='2D', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=8, help_text='Number of rows (e.g. 8 for A-H)')),
                ('seats_per_row', models.PositiveIntegerField(default=10, help_text='Seats per row (e.g. 10)')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theater')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen'),
        ),
        migrations.AddField(
            model_name='showschedule',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='movies.screen'),
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='movies.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_bookings', to='movies.seat')),
                ('show_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='movies.showschedule')),
            ],
            options={
                'unique_together': {('show_schedule', 'seat')},
            },
        ),
    ]
