# Generated by Django 3.2.19 on 2026-08-03 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_auto_20260802_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked')], default='available', max_length=10)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_seats', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='movies.seat')),
                ('show_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='movies.showschedule')),
            ],
            options={
                'ordering': ['seat__row', 'seat__number'],
            },
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show_schedule', 'status'], name='movies_show_show_sc_13d13a_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['reserved_until'], name='movies_show_reserve_1d7812_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showseat',
            unique_together={('show_schedule', 'seat')},
        ),
    ]
