# Generated by Django 3.2.19 on 2026-08-04 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20260803_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe')], default='razorpay', max_length=20)),
                ('gateway_order_id', models.CharField(help_text='Order ID returned by the payment gateway (e.g. order_xxx from Razorpay)', max_length=255, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID returned by the gateway after payment attempt', max_length=255)),
                ('gateway_signature', models.CharField(blank=True, help_text='Signature for server-side verification (Razorpay)', max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in base currency units (e.g. INR)', max_digits=10)),
                ('amount_paise', models.PositiveIntegerField(default=0, help_text='Amount in smallest currency unit sent to gateway (paise for INR)')),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_response', models.TextField(blank=True, help_text='Raw JSON response from gateway — stored for audit/dispute resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='movies.booking')),
                ('show_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movies.showschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_order_id'], name='movies_paym_gateway_e04bda_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='movies_paym_user_id_00a9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='movies_paym_status_5316c9_idx'),
        ),
    ]
