# Generated by Django 3.2.19 on 2026-08-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20260804_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movies.showschedule'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='show_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='movies.showschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='showschedule',
            unique_together={('screen', 'show_time')},
        ),
    ]
