# Generated by Django 3.2.19 on 2026-08-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20260805_1235'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_status_5316c9_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-booked_at'], name='movies_book_status_671b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'status'], name='movies_book_movie_i_cb8d13_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'status'], name='movies_book_theater_e79b80_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show_schedule', 'status'], name='movies_book_show_sc_907ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='movies_paym_status_10d5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='movies_paym_created_5e9beb_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['show_time'], name='movies_show_show_ti_497c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['movie', 'show_time'], name='movies_show_movie_i_61d170_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['theater', 'show_time'], name='movies_show_theater_60aa25_idx'),
        ),
    ]
