# Generated by Django 3.2.19 on 2026-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20260807_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.FileField(blank=True, help_text='Generated PDF ticket', null=True, upload_to='tickets/'),
        ),
    ]
