# Generated by Django 3.2.19 on 2026-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20260808_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_pdf_data',
            field=models.BinaryField(blank=True, help_text='Raw PDF ticket bytes stored directly in DB for cloud persistence', null=True),
        ),
    ]
